mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰转下划线配置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #配置日志输出
  global-config:
    db-config:
      id-type: auto # 数据库id自增
  type-aliases-package: team.weilai.studythrough.pojo

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xxxx:3306/study_db
    username:
    password:
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 2048MB
  redis:
    host:
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 15
        min-idle: 0
        max-idle: 8
        max-wait: 100
    timeout: 1000
    database: 5
  # 定时任务配置
  quartz:
    # 数据库方式
    job-store-type: jdbc
    # quartz 相关属性配置
    properties:
      org:
        quartz:
          scheduler:
            instanceName: stScheduler
            instanceId: AUTO
          jobStore:
            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true
            clusterCheckinInterval: 10000
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
#  elasticsearch:
#    username: elastic
#    password: 211322GWj@es
#    uris: http://47.121.129.110:9200

minio:
  endpoint: http://xxxx:9000
  accesskey:
  secretkey:
  bucket: study
  expiry: 1 # redis 文件信息失效时间 天
  breakpointTime: 1 # 分片地址失效时间 天
  tempBucket: temp-file

model:
  models:
    - name: Ultra
      hostUrl: https://spark-api.xf-yun.com/v4.0/chat
      apiKey:
      apiSecret:
      appId:
      uploadUrl: https://spark-api.xf-yun.com/v4.0/chat
      apiPassword:
      domain: 4.0Ultra
    - name: Max
      hostUrl: https://spark-api.xf-yun.com/v3.5/chat
      apiKey:
      apiSecret:
      appId:
      uploadUrl: https://spark-api.xf-yun.com/v3.5/chat
      apiPassword:
      domain: generalv3.5

